default-config: &default-config
  docker:
    - image: circleci/node:8.11-browsers
  working_directory: ~/repo

version: 2.1
jobs:
  build:
    <<: *default-config
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            - deps-{{ checksum "package.json" }}-
            - deps-
      - run:
          name: Install dependencies
          command: |
            npm install --no-save
      - save_cache:
          key: deps-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - src/node_modules
      - run:
          name: Run the Unit Tests
          command: |
            npm run test
      - run:
          name: Build
          command: |
            npm run build
      - persist_to_workspace:
          root: /
          paths:
            - config/deploy
            - .git

  create-release:
    <<: *default-config
    environment:
      NODE_ENV: production
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install deploy dependencies
          command: |
            npm install --prefix . git-rev-sync @octokit/rest
      - run:
          name: Create Release
          command: |
            cd config/deploy
            node create-release.js


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - create-release:
          requires:
            - build
          filters:
            branches:
              only: master
